import path from "node:path";
import type { Finding, ScanReport, Severity } from "./types.ts";

const icon: Record<Severity, string> = {
  high: "✖",
  medium: "▲",
  low: "●",
  info: "○",
};

function location(finding: Finding): string {
  if (!finding.file) return "project";
  return finding.line ? `${finding.file}:${finding.line}` : finding.file;
}

export function toText(report: ScanReport, color = true): string {
  const ansi = {
    reset: color ? "\u001b[0m" : "",
    bold: color ? "\u001b[1m" : "",
    high: color ? "\u001b[31m" : "",
    medium: color ? "\u001b[33m" : "",
    low: color ? "\u001b[36m" : "",
    info: color ? "\u001b[90m" : "",
  };
  const lines = [
    `${ansi.bold}MesaGuard — o1js 3 / Mesa migration preflight${ansi.reset}`,
    `Project: ${report.project.name}`,
    `o1js: ${report.project.o1js.declared ?? "not declared"}${report.project.o1js.resolved ? ` (resolved ${report.project.o1js.resolved})` : ""}`,
    `Verdict: ${report.summary.verdict.toUpperCase()} · ${report.summary.high} high · ${report.summary.medium} medium · ${report.summary.low} low`,
    "",
  ];

  if (report.findings.length === 0) {
    lines.push("No static migration findings. This is not proof of deployment or circuit safety.");
  }
  for (const finding of report.findings) {
    lines.push(
      `${ansi[finding.severity]}${icon[finding.severity]} ${finding.severity.toUpperCase()} ${finding.ruleId}${ansi.reset} ${finding.title}`,
      `  ${location(finding)} — ${finding.message}`,
      `  Fix: ${finding.remediation}`,
    );
    if (finding.excerpt) lines.push(`  > ${finding.excerpt}`);
    lines.push("");
  }
  lines.push(
    `Scanned ${report.summary.filesScanned} source files. Static preflight only.`,
    `Source: ${report.sources[0]?.url ?? ""}`,
  );
  return lines.join("\n");
}

function escapeTable(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

export function toMarkdown(report: ScanReport): string {
  const version = report.project.o1js.declared
    ? `\`${report.project.o1js.declared}\`${
        report.project.o1js.resolved ? ` (resolved \`${report.project.o1js.resolved}\`)` : ""
      }`
    : "Not declared";
  const rows = report.findings.map(
    (finding) =>
      `| ${finding.severity.toUpperCase()} | ${finding.ruleId} | ${escapeTable(finding.title)} | \`${escapeTable(location(finding))}\` |`,
  );
  return `# MesaGuard migration preflight

| | |
|---|---|
| Project | **${escapeTable(report.project.name)}** |
| o1js | ${version} |
| Target | o1js 3.x / Mesa |
| Verdict | **${report.summary.verdict.toUpperCase()}** |
| Findings | ${report.summary.high} high · ${report.summary.medium} medium · ${report.summary.low} low |
| Source files scanned | ${report.summary.filesScanned} |

${
  rows.length
    ? `## Findings\n\n| Severity | Rule | Finding | Location |\n|---|---|---|---|\n${rows.join("\n")}\n\n${report.findings
        .map(
          (finding) => `### ${finding.ruleId} — ${finding.title}\n\n${finding.message}\n\n**Migration action:** ${finding.remediation}${finding.excerpt ? `\n\n> ${finding.excerpt}` : ""}`,
        )
        .join("\n\n")}`
    : "## Findings\n\nNo static migration findings."
}

## Boundaries

${report.limitations.map((item) => `- ${item}`).join("\n")}

## Official evidence

${report.sources.map((source) => `- [${source.label}](${source.url})`).join("\n")}

_Generated by MesaGuard ${report.tool.version} at ${report.generatedAt}. Repository path reduced to ${path.basename(report.project.path)} in this Markdown output._
`;
}

export function toJson(report: ScanReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}
